server: 
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://PGPASSWORD=xA51T5Mu8jgytBVMimG06XfUpXXJrugy psql -h dpg-cstjual6l47c73elvejg-a.oregon-postgres.render.com -U banco_ay89_user banco_ay89
        username: banco_ay89_user
        password: xA51T5Mu8jgytBVMimG06XfUpXXJrugy
        driver-class-name: org.postgresql.Driver
        initialize: true
    
    jpa:
        hibernate:
            ddl-auto: create-drop
            generate-ddl: true
            show-sql: true #mostra sql query no console
        
    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres
