server: 
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/dbzinho
        username: postgres
        password: 123456
        driver-class-name: org.postgresql.Driver
        initialize: true
    
    jpa:
        hibernate:
            ddl-auto: create-drop
            generate-ddl: true
            show-sql: true #mostra sql query no console
        
    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres
